export const reactQueryKeys = {
  posts: "posts",
  postDetail: "postDetail",
  dialogs: "dialogs",
  dialogDetail: "dialogDetail",
  friends: "friends",
  videos: "videos",
  music: "music",
  userDetail: "userDetail",
  userPosts: "userPosts",
  userCommunities: "userCommunities",
  userVideos: "userVideos",
  userFriends: "userFriends",
  postComments: "postComments",
  postCommentReplies: "postCommentReplies",
  videoComments: "videoComments",
  userFollowers: "userFollowers",
  userFollowing: "userFollowing",
  userMusic: "userMusic",
  userMusicPlaylists: "userMusicPlaylists",
  videoDetail: "videoDetail",
  userSettings: "userSettings",
  playlistDetail: "playlistDetail",
  playlistSongs: "playlistSongs",
  playlistPreview: "playlistPreview",
  videoCommentReplies: "videoCommentReplies",
  playlists: "playlists"
};
